open Printf


let string_of_string s = "\"" ^ String.escaped(s) ^ "\""


let string_of_Loc__source = function
  | Loc.InFile f     ->  "Loc.InFile " ^ (string_of_string f)
  | Loc.ToplevelInput -> "Loc.ToplevelInput"


let string_of_Loc__t {Loc.fname; line_nb; bol_pos; line_nb_last; bol_pos_last; bp; ep} =
  sprintf "Loc.t{Loc.fname = %s; Loc.line_nb = %d; Loc.bol_pos = %d; Loc.line_nb_last = %d; Loc.bol_pos_last = %d; Loc.bp = %d; Loc.ep = %d}"
   (string_of_Loc__source fname) line_nb bol_pos line_nb_last bol_pos_last bp ep


let vernac_expr_type = function
  | Vernacexpr.VernacLoad _ -> "VernacLoad"
  | Vernacexpr.VernacSyntaxExtension _ -> "VernacSyntaxExtension"
  | Vernacexpr.VernacOpenCloseScope _ -> "VernacOpenCloseScope"
  | Vernacexpr.VernacDelimiters _ -> "VernacDelimiters"
  | Vernacexpr.VernacBindScope _ -> "VernacBindScope"
  | Vernacexpr.VernacInfix _  -> "VernacInfix"
  | Vernacexpr.VernacNotation _ -> "VernacNotation"
  | Vernacexpr.VernacNotationAddFormat _ -> "VernacNotationAddFormat"
  | Vernacexpr.VernacDeclareCustomEntry _ -> "VernacDeclareCustomEntry"
  | Vernacexpr.VernacDefinition _ -> "VernacDefinition"
  | Vernacexpr.VernacStartTheoremProof _ -> "VernacStartTheoremProof"
  | Vernacexpr.VernacEndProof _ -> "VernacEndProof"
  | Vernacexpr.VernacExactProof _ -> "VernacExactProof"
  | Vernacexpr.VernacAssumption _ -> "VernacAssumption"
  | Vernacexpr.VernacInductive _ -> "VernacInductive"
  | Vernacexpr.VernacFixpoint _ -> "VernacFixpoint"
  | Vernacexpr.VernacCoFixpoint _ -> "VernacCoFixpoint"
  | Vernacexpr.VernacScheme _ -> "VernacScheme"
  | Vernacexpr.VernacCombinedScheme _ -> "VernacCombinedScheme"
  | Vernacexpr.VernacUniverse _ -> "VernacUniverse"
  | Vernacexpr.VernacConstraint _ -> "VernacConstraint"
  | Vernacexpr.VernacBeginSection _ -> "VernacBeginSection"
  | Vernacexpr.VernacEndSegment _ -> "VernacEndSegment"
  | Vernacexpr.VernacRequire _ -> "VernacRequire"
  | Vernacexpr.VernacImport _ -> "VernacImport"
  | Vernacexpr.VernacCanonical _ -> "VernacCanonical"
  | Vernacexpr.VernacCoercion _ -> "VernacCoercion"
  | Vernacexpr.VernacIdentityCoercion _ -> "VernacIdentityCoercion"
  | Vernacexpr.VernacNameSectionHypSet _ -> "VernacNameSectionHypSet"
  | Vernacexpr.VernacInstance _ -> "VernacInstance"
  | Vernacexpr.VernacContext _ -> "VernacContext"
  | Vernacexpr.VernacDeclareInstances _ -> "VernacDeclareInstances"
  | Vernacexpr.VernacDeclareClass _ -> "VernacDeclareClass"
  | Vernacexpr.VernacDeclareModule _ -> "VernacDeclareModule"
  | Vernacexpr.VernacDefineModule _ -> "VernacDefineModule"
  | Vernacexpr.VernacDeclareModuleType _ -> "VernacDeclareModuleType"
  | Vernacexpr.VernacInclude _ -> "VernacInclude"
  | Vernacexpr.VernacSolveExistential _ -> "VernacSolveExistential"
  | Vernacexpr.VernacAddLoadPath _ -> "VernacAddLoadPath"
  | Vernacexpr.VernacRemoveLoadPath _ -> "VernacRemoveLoadPath"
  | Vernacexpr.VernacAddMLPath _ -> "VernacAddMLPath"
  | Vernacexpr.VernacDeclareMLModule _ -> "VernacDeclareMLModule"
  | Vernacexpr.VernacChdir _ -> "VernacChdir"
  | Vernacexpr.VernacWriteState _ -> "VernacWriteState"
  | Vernacexpr.VernacRestoreState _ -> "VernacRestoreState"
  | Vernacexpr.VernacResetName _ -> "VernacResetName"
  | Vernacexpr.VernacResetInitial -> "VernacResetInitial"
  | Vernacexpr.VernacBack i -> "VernacBack"
  | Vernacexpr.VernacBackTo i -> "VernacBackTo"
  | Vernacexpr.VernacCreateHintDb _ -> "VernacCreateHintDb"
  | Vernacexpr.VernacRemoveHints _ -> "VernacRemoveHints"
  | Vernacexpr.VernacHints _ -> "VernacHints"
  | Vernacexpr.VernacSyntacticDefinition _ -> "VernacSyntacticDefinition"
  | Vernacexpr.VernacArguments _ -> "VernacArguments"
  | Vernacexpr.VernacReserve _ -> "VernacReserve"
  | Vernacexpr.VernacGeneralizable _ -> "VernacGeneralizable"
  | Vernacexpr.VernacSetOpacity _ -> "VernacSetOpacity"
  | Vernacexpr.VernacSetStrategy _ -> "VernacSetStrategy"
  | Vernacexpr.VernacUnsetOption _ -> "VernacUnsetOption"
  | Vernacexpr.VernacSetOption _ -> "VernacSetOption"
  | Vernacexpr.VernacAddOption _ -> "VernacAddOption"
  | Vernacexpr.VernacRemoveOption _ -> "VernacRemoveOption"
  | Vernacexpr.VernacMemOption _ -> "VernacMemOption"
  | Vernacexpr.VernacPrintOption _ -> "VernacPrintOption"
  | Vernacexpr.VernacCheckMayEval _ -> "VernacCheckMayEval"
  | Vernacexpr.VernacGlobalCheck _ -> "VernacGlobalCheck"
  | Vernacexpr.VernacDeclareReduction _ -> "VernacDeclareReduction"
  | Vernacexpr.VernacPrint _ -> "VernacPrint"
  | Vernacexpr.VernacSearch _ -> "VernacSearch"
  | Vernacexpr.VernacLocate _ -> "VernacLocate"
  | Vernacexpr.VernacRegister _ -> "VernacRegister"
  | Vernacexpr.VernacComments _ -> "VernacComments"
  | Vernacexpr.VernacAbort _ -> "VernacAbort"
  | Vernacexpr.VernacAbortAll -> "VernacAbortAll"
  | Vernacexpr.VernacRestart -> "VernacRestart"
  | Vernacexpr.VernacUndo _ -> "VernacUndo"
  | Vernacexpr.VernacUndoTo _ -> "VernacUndoTo"
  | Vernacexpr.VernacFocus _ -> "VernacFocus"
  | Vernacexpr.VernacUnfocus -> "VernacUnfocus"
  | Vernacexpr.VernacUnfocused -> "VernacUnfocused"
  | Vernacexpr.VernacBullet _ -> "VernacBullet"
  | Vernacexpr.VernacSubproof _ -> "VernacSubproof"
  | Vernacexpr.VernacShow _ -> "VernacShow"
  | Vernacexpr.VernacEndSubproof -> "VernacEndSubproof"
  | Vernacexpr.VernacCheckGuard -> "VernacCheckGuard"
  | Vernacexpr.VernacProof _ -> "VernacProof"
  | Vernacexpr.VernacProofMode _ -> "VernacProofMode"
  | Vernacexpr.VernacExtend _ -> "VernacExtend"